services:
  - type: web
    name: eleicoes-brasil-api
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: APP_MODE
        value: PRODUCTION
      - key: COLLECTOR_ROUND_SLUG
        value: 2026-1
      - key: COLLECTOR_IGNORE_WINDOWS
        value: "false"
      - key: TSE_PROVIDER_ROUND_ID
        value: "3220"
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: DB_MIGRATION_USER
        sync: false
      - key: DB_MIGRATION_PASSWORD
        sync: false
      - key: DB_APP_USER
        sync: false
      - key: DB_APP_PASSWORD
        sync: false
      - key: CORS_ORIGINS
        value: http://localhost:4200,https://eleicoes-brasil.pages.dev
      - key: ELECTION_WINDOWS
        value: 2026-10-04T17:00-03:00/2026-10-05T22:00-03:00,2026-10-25T17:00-03:00/2026-10-26T22:00-03:00
